### ISSUE TITLE
[Suggestion] Would you like to move this project to the doccano organization?

### ISSUE THREAD

**Issue by Hironsan** [doccano/doccano_api_client#3]
Hello, @afparsons 

First of all, I really appreciate your project. It makes easier to programmatically manipulate doccano.

I have a suggestion. Would you like to move this project to the [doccano organization](https://github.com/doccano)? If you accept it, I'll invite you to the organization and the doccano-client team and then give you the role on the team.

It would be much appreciated if you could consider the suggestion.

**Comment by afparsons** [comment]
Hi @Hironsan ,

This is flattering; thank you for the invite.

I do think it makes sense to move this project under the umbrella of the [doccano organization](https://github.com/doccano). After all, users will probably expect doccano-related projects to be attached to the organization, and I didn't expect this repository to offer a permanent solution in the first place.

Have you moved a GitHub project before? I've not done so, so I am not really sure about the next steps. There's probably a more elegant solution than just starting a new repository, and copy/pasting code, right?

**Comment by Hironsan** [comment]
Hi @afparsons ,
I just invited you to the organization.

> Have you moved a GitHub project before?

Yes. GitHub provides the feature to transfer a repository. This is the easiest way.
- [Transferring a repository owned by your personal account](https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/)

After transferring the repository, I will create doccano-client team and add you to it.

Thanks.

**Comment by kuraga** [comment]
@afparsons , ping.

**Comment by harmw** [comment]
what needs to happen to close this one 🙈 as it would be really nice to get this in the main project 👍

**Comment by afparsons** [comment]
Hi @kuraga , @harmw , and @Hironsan !

I'm sorry, I find GitHub's notifications difficult to work with and so a lot disappears into the void. I'll move this right now.

**Comment by afparsons** [comment]
Oops, I let @Hironsan's organizational invite expire, so they will need to re-inivite me to the organization.

@Hironsan Could you please invite me again? I promise to accept and transfer the repository this time :smile: 

@kuraga, @harmw it might be a few moments. Sorry about the wait.

**Comment by Hironsan** [comment]
Hello @afparsons 

I just re-invite you to the organization.

**Comment by afparsons** [comment]
I have transferred repository ownership to doccano.

**Comment by kuraga** [comment]
:÷1:

**Comment by Hironsan** [comment]
Thank you!
